// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tenka.Data;

#nullable disable

namespace Tenka.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tenka.Models.Household", b =>
                {
                    b.Property<int>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HouseholdId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WaterTankId")
                        .HasColumnType("int");

                    b.HasKey("HouseholdId");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("Tenka.Models.WaterTank", b =>
                {
                    b.Property<int>("WaterTankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WaterTankId"));

                    b.Property<bool>("Shutoff")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WaterLevel")
                        .HasColumnType("int");

                    b.HasKey("WaterTankId");

                    b.ToTable("WaterTanks");
                });
#pragma warning restore 612, 618
        }
    }
}
